def GlobalConfig
pipeline {
    agent any

    post {
        success {
            echo "SUCCESS"
            // mail(to:"alejandro.maillard@getronics.com",
            //         subject: "[${env.ENTORNO}] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) ejecutado",
            //         body: "El Job ha finalizado: ${env.BUILD_URL}. Referencia: ${config?.REF}\n  Sonar: ${env.SONARURL}")
        }
        failure {
            echo "FAILURE"
            // mail(to:"alejandro.maillard@getronics.com",
            //         subject: "[${env.ENTORNO}] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) ejecutado con errores",
            //         body: "El Job ha finalizado con errores: ${env.BUILD_URL}. Referencia: ${config?.REF}\n ")
        }
        unstable {
            echo "UNSTABLE"
            // mail(to:"alejandro.maillard@getronics.com",
            //         subject: "[${env.ENTORNO}] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) inestable",
            //         body: "El Job ha finalizado: ${env.BUILD_URL}. Referencia: ${config?.REF}\n  Sonar: ${env.SONARURL}")
        }
    }

    stages {
        stage('Validate Config') {
            steps {
                script {
                    try {
                        echo "Configuracion cargada"
                        //Lectura del fichero de configuracion, asociado por nombre de la tarea
                        echo env.JOB_NAME
                        config = utilConfig(env.JOB_NAME)
                        echo "Configuracion cargada"
                    } catch (Exception e) {
                        echo e.toString()
                        throw e
                    }


                    //Comprobar que el Job contiene los parametros necesarios
                    utilJobParams(params, config)
                    try {

                        echo "MENSAJE DATOS TAREA JENKINS " env.ENTORNO " "  env.BUILD_NUMBER " " env.BUILD_URL
                        // utilHelper.retry({
                        //     mail(to: "alejandro.maillard@getronics.com",
                        //             subject: "[${env.ENTORNO}] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) iniciado",
                        //             body: "El Job se ha iniciado: ${env.BUILD_URL}. ")
                        // })
                    } catch (Exception e) {
                        echo e.toString()
                    }
                }
            }
        }

        // stage('Checkout') {
        //     steps {

        //         utilCheckout(config)

        //     }
        // }

        // stage('Build') {
        //     steps {
        //          utilBuild(config)
        //     }
        // }
        // stage('Testing') {
        //     steps {
        //         utilTest(config)
        //     }

        // }
        // stage('Code Quality') {
        //     when {
        //         expression { config.SONAR == 'SI' }
        //     }
        //     steps {
        //         utilCodeQuality(config)
        //     }
        // }

    }
}
